package com.training.classes;

public class Employee {
	private long empId; // autogenerated
	private String name;
	private String email;
	private Address address; // plot,street,city,state -- association -- Has a relation
	private static  int count; //0 as default
	
	public static int getCount()
	{
		return count;
	}
	
	public Employee() {
		empId=++count;
	}
	public Employee(String name, String email,Address address) {
		this.empId = ++count;
		this.name = name;
		this.email = email;
		this.address=address;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
	public long getEmpId() {
		return empId;
	}
	
	public void travels(Car car) // dependency
	{
		System.out.println(name+" travels by "+car.getColor()+" "+car.getModel()+ " Car");
	}

	public void livesIn()
	{
		System.out.println(name+" lives in"+address.getPlotNo()+","+address.getStreet()+","+address.getCity());
		
	}
}
